spring.application.name=LMOrderMS
#puerto designado sin eureka corriendo:
#server.port=8085

#Con Eureka, dejamos el puerto 0 para que sea Eureka quien designe puertos automáticamente con la configuración que sigue abajo.
server.port=0
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/

##Lo siguiente crea un ID único y aleatorio para el servicio y, así, evitar que choquen entre sí.
eureka.instance.instance-id=${spring.application.name}:${random.value}

#Esto obliga a Eureka a mostrar el puerto real en su dashboard.
eureka.instance.prefer-ip-address=true


#####BD MySQL######:
spring.datasource.url=jdbc:mysql://localhost:3306/order_db
#                           servicio://dirección:puerto/nombre_de_la_bd

# Required credentials
spring.datasource.username=root
spring.datasource.password=

#Confg de Spring con MySQL:
spring.jpa.hibernate.ddl-auto=create-drop
#Solo utilizamos create-drop al estar creando las entidades y configurando la BD. Una vez definida, debemos trabajar con update:
#spring.jpa.hibernate.ddl-auto=update


#El sig. código muestra un pseudocódigo SQL por consola para saber qué procedimiento SQL se está ejecutando.
spring.jpa.show-sql=true

#El sig. código le da el formato típico SQL al pseudocódigo mostrado por consola (si está activado el show-sql).
spring.jpa.properties.hibernate.format_sql=true

#El sig. código define el dialecto de SQL a utilizar. En este caso, de MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

######LOGS######:
#LAS SIGUIENTES LÍNEAS SOLO CONFIGURAN LOGS SALIENDO POR CONSOLA.

## Niveles/capas y grupos de acción de Logging:
#ROOT: desde nivel raíz, incluyendo to_do
#SQL: nivel de base de datos SQL
#WEB: a nivel web incluyendo codecs
#A NIVEL DE PAQUETES (ej: com.exampple.miApp)

## Tipos de logging:
#DEBUG: Info detallada para desarrollo y depuración.
#INFO: Info general sobre el funcionamiento de aplicación.
#WARN: Advertencia sobre potenciales problemas.
#ERROR: errores de ejecución/funcionamiento.

## Nivel de log global:
#INFO:
#WARN:
#ERROR:
logging.level.root=INFO

#Logs por paquete:
logging.level.cl.duoc.demoBDpersonas=DEBUG

#CONVERSIÓN Y COMUNICACIÓN A BD
logging.level.org.hibernate=ERROR

#formato del log con "pattern" se define el patrón de formato que incluye: timestamp, nivel de log, clase, y mensaje.
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{50} - %msg%n
#-5 en "-5level" indica alineación a la izquierda con nombre de nivel de 5 caracteres de largo máximo.
# %logger{x} siendo x un número, indica el largo de caracteres del nombre del logger. Por lo general, 20 es muy corto, 36 es el punto medio, 50 es más detallado. No colocar número expone a nombres que pueden ser demasiado largos.
#- %msg%n agrega mensaje y salto de línea.

##GUARDAR LOS LOGS EN UN ARCHIVO PARA SU REGISTRO Y QUE NO SOLO QUEDEN EN CONSOLA:

#Nombre del archivo de logs del proyecto:
logging.file.name=LMOrderMS.log

#Define la retención de archivos. Es decir, por cuántos días se mantendrá el historial de logs diarios. Trabaja con la diferencia real de días desde el primer log de un nuevo período de retención.
logging.logback.rollingpolicy.max-history=30

#Define en qué formato se guardarán los logs en el archivo de logs:
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{50} - %msg%n

#Configuración de documentación:
#Api-doc:
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api/v1/pedidos/v3/api-docs
#/v3/api-docs es solo la ruta por convención, y v3 refiere a la versión de api-doc. Puede ser cualquier ruta.